### ISSUE TITLE
Extension not working anymore after ubuntu upgrade

### ISSUE THREAD

**Issue by ruzito** [yannishuber/pass-ulauncher#8]
After ubuntu upgrade the extension showed crash status.
After extension reinstall clicking on save button in the extension settings results in this error.

Message: 'com.github.yannishuber.pass-ulauncher'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.yannishuber.pass-ulauncher'

```

**Comment by ruzito** [comment]
Sorry it's not working on my side
